/**
 * @link 详细配置信息参考官方网站 http://stylelint.docschina.org/user-guide/rules/
 * 默认警告类型为error，可使用severity改变警告类型
 */
module.exports = {
  extends: ["stylelint-config-standard", "stylelint-config-prettier"].map(require.resolve),
  plugins: [
    "stylelint-order",
    "stylelint-declaration-block-no-ignored-properties",
    "stylelint-scss",
  ],
  rules: {
    "order/order": ["custom-properties", "declarations"],
    "order/properties-order": [
      "overflow",
      "overflow-x",
      "overflow-y",
      "clip",
      "clear",
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "float",
      "width",
      "height",
      "max-width",
      "max-height",
      "min-width",
      "min-height",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "margin-collapse",
      "margin-top-collapse",
      "margin-right-collapse",
      "margin-bottom-collapse",
      "margin-left-collapse",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "background",
      "background-color",
      "border",
      "border-radius",
      "color",
      "font",
      "font-family",
      "font-size",
      "font-smoothing",
      "osx-font-smoothing",
      "font-style",
      "font-weight",
      "line-height",
      "letter-spacing",
      "word-spacing",
      "text-align",
      "text-decoration",
      "text-indent",
      "text-overflow",
      "text-rendering",
      "text-size-adjust",
      "text-shadow",
      "text-transform",
      "word-break",
      "word-wrap",
      "white-space",
      "vertical-align",
      "list-style",
      "list-style-type",
      "list-style-position",
      "list-style-image",
      "content",
      "outline",
      "outline-offset",
      "filter",
      "visibility",
      "size",
      "opacity",
      "transform",
      "cursor",
      "pointer-events",
    ],
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": null,
    "import-notation": null,
    "selector-class-pattern": null,
  },
  overrides: [
    {
      files: ["*.scss", "**/*.scss"],
      customSyntax: "postcss-scss",
    },
    {
      files: ["*.less", "**/*.less"],
      customSyntax: "postcss-less",
    },
  ],
  ignoreFiles: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.json"],
}
